--
-- Tabella dei flussi individuati/classificati
--
CREATE TABLE dID_items (
  id SERIAL NOT NULL PRIMARY KEY,
  dataset_id INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE ON UPDATE CASCADE,
  capfile_id INTEGER NOT NULL REFERENCES capfiles(id) ON DELETE CASCADE ON UPDATE CASCADE,
  cdate DATE NOT NULL DEFAULT '0001-01-01',
  ctime TIME NOT NULL DEFAULT '00:00:00',
  year INTEGER,
  month INTEGER,
  week INTEGER,
  hour INTEGER,
  min5 INTEGER,
  days INTEGER,
  seconds INTEGER,
  flow_info VARCHAR( 255 ) NOT NULL,
  metadata VARCHAR( 255 ),
  classification_id INTEGER REFERENCES classifications(id) DEFAULT 1,
  ip_src VARCHAR( 64 ),
  ip_dst VARCHAR( 64 ),
  ips_id INTEGER,
  ipd_id INTEGER,
  dns VARCHAR( 1024 ),
  port_src INTEGER,
  port_dst INTEGER,
  port_grp INTEGER,
  l4prot VARCHAR(55),
  l7prot VARCHAR(55),
  lat REAL,
  long REAL,
  country VARCHAR( 10 ),
  country_src VARCHAR( 10 ),
  bsent BIGINT,
  brecv BIGINT,
  blsent BIGINT,
  blrecv BIGINT,
  pktsent INTEGER,
  pktrecv INTEGER,
  tracesent VARCHAR( 255 ),
  tracerecv VARCHAR( 255 ),
  images VARCHAR( 255 ),
  duration INTEGER,
  start_pkt BIGINT,
  offset_pkt BIGINT,
  eth_src VARCHAR(25),
  eth_dst VARCHAR(25),
  encaps VARCHAR( 255 ),
  notes INTEGER
);

ALTER TABLE dID_items OWNER TO capana;
